name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    env: # Set the secret as an input
        DOCKER_ID: ${{ secrets.DOCKER_ID }}
        PROJECT: ${{ secrets.PROJECT }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        GIT_SHA: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
          # version: '274.0.1'
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}
      #  gcloud config set project room-book-264007
    - run: |
         gcloud info

    - name: Build the Docker image
      run: |
        docker build --file Dockerfile -t $DOCKER_ID/$PROJECT-client:latest -t $DOCKER_ID/$PROJECT-client:$GIT-SHA  .
    - name: Log in to the docker CLI
      run: |
       echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID  --password-stdin
    - name: Take latest images and push it to docker hub
      run:  |
        docker push $DOCKER_ID/$PROJECT-client:latest
    - name: Take sha images and push it to docker hub
      run:  |
        docker push $DOCKER_ID/$PROJECT-client:$GIT-SHA
