name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env: # Set the secret as an input
        DOCKER_ID: ${{ secrets.DOCKER_ID }}
        PROJECT: ${{ secrets.PROJECT }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build --file Dockerfile -t $DOCKER_ID/$PROJECT-client .
    - name: Log in to the docker CLI
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID  --password-stdin
    - name: Take those images and push them to docker hub
      run:  docker push $DOCKER_ID/$PROJECT-client
